spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    password: 123
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/room
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 8087
  error:
    include-message: always
feign:
  front:
    url: http://localhost:8080
  mail:
    url: http://localhost:8081
  employee:
    url: http://localhost:8085
  profile:
    url: http://localhost:8086