mail:
  debug: 'true'
spring:
  datasource:
    password: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/room
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 8083
  error:
    include-message: always
feign:
  mail:
    url: http://localhost:8081
  employee:
    url: http://localhost:8085
  profile:
    url: http://localhost:8086